### ISSUE TITLE
HELP migrating from K911 original package

### ISSUE THREAD

**Issue by mpoiriert** [symfony-swoole/swoole-bundle#77]
I am migrating from the K911 original package that is not maintained anymore.

Server is starting but I get an error using BloomRPC (using GRPC).

I am using openswoole.

This is the error I get when I put level to debug:

TRACE	Port_onRead_http() (ERRNO 7102): Bad Request: unknown protocol from session#3 on 0.0.0.0:50051

(I am running on port 50051).

I am not the original developer that setup grpc and swoole in the first place (they are not working in the company anymore).

If you have any idea to help me pin point the problem let me know.

**Comment by Rastusik** [comment]
Hey @mpoiriert ! I'm not aware that this bundle supports GRPC, there is only HTTP support AFAIK. It looks like there is some custom modification been made in your project.
Not sure if I can help you with this.

**Comment by mpoiriert** [comment]
@Rastusik The fact that I use grpc should not affect swoole. The protocole is still http but the payload is in binary and deserialize within symfony. From the error message I am not event reaching symfony....

**Comment by Rastusik** [comment]
@mpoiriert I understand what you mean but you are describing something that is in no way supported (yet) by this bundle. There is no code in the bundle for what you mention here (grpc to http bridge). It seems like you need to fix your custom integration to be able to work this out.
