### ISSUE TITLE
SF 6.4 - there are no logs being shown in the symfony profiler

### ISSUE THREAD

**Issue by pistej** [symfony-swoole/swoole-bundle#86]
Since symfony 6.4 `AddDebugLogProcessorPass` dperecated function `configureLogger`  and change `debug_logger_configurator`, so it seems DebugLogProcessorPass class from bundle is not correct/needed anymore.

MR with sf change: https://github.com/symfony/symfony/pull/52079/files#diff-e4f52d5033296421d02e360c8355aa1931bdfb0c12579f4815ea02b724322c0cL1179

https://symfony.com/doc/current/reference/configuration/kernel.html#kernel-runtime-mode

Simple fix can be remove class `DebugLogProcessorPass` and set sf. parameter: `kernel.runtime_mode.web: true` which is used as second param in DebugLoggerConfigurator

**Comment by Rastusik** [comment]
@pistej thank you for the contribution, much appreciated! Looks like the CI pipeline is stuck again, though. I will try to investigate next week and maybe also enable the debug log pass conditionally only for SF 5.4.
